#include "TCGHybridBasicGlobalVariableRegister.h"
#include "define.h"
#include "TCGHybridBasic.h"
void TCGHybridBasicGlobalVariableRegister::registAllGlobalVariables()
{
    vector<int> arraySizeOf_DynamicCompressionModel_instance_Timing_TaskCounters_TID = {2};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_instance.Timing.TaskCounters.TID", "u16", arraySizeOf_DynamicCompressionModel_instance_Timing_TaskCounters_TID, (char*)(&(DynamicCompressionModel_instance.Timing.TaskCounters.TID)), sizeof(unsigned short) * 2);
    vector<int> arraySizeOf_DynamicCompressionModel_instance_Timing_clockTick0;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_instance.Timing.clockTick0", "u32", arraySizeOf_DynamicCompressionModel_instance_Timing_clockTick0, (char*)(&(DynamicCompressionModel_instance.Timing.clockTick0)), sizeof(unsigned int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter2_circBuf;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter2_circBuf", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter2_circBuf, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter2_circBuf)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter1_circBuf;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter1_circBuf", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter1_circBuf, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter1_circBuf)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter3_circBuf;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter3_circBuf", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter3_circBuf, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter3_circBuf)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter4_circBuf;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter4_circBuf", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter4_circBuf, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter4_circBuf)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter5_circBuf;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter5_circBuf", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter5_circBuf, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter5_circBuf)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ig65fir_circBuf;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ig65fir_circBuf", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ig65fir_circBuf, (char*)(&(DynamicCompressionModel_DW_instance.ig65fir_circBuf)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_h = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_h", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_h, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_h)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_a = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_a", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_a, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_a)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_n = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_n", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_n, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_n)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_o = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_o", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_o, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_o)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_k = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_k", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_k, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_k)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_c = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_c", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_c, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_c)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_c5 = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_c5", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_c5, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_c5)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_hz = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_hz", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_hz, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_hz)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_hp = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_DSTATE_hp", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_DSTATE_hp, (char*)(&(DynamicCompressionModel_DW_instance.ram_DSTATE_hp)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_1_DSTATE = {26};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.dly_shift_1_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_1_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.dly_shift_1_DSTATE)), sizeof(int) * 26);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter2_states = {628};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter2_states", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter2_states, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter2_states)), sizeof(int) * 628);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_3_DSTATE = {138};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.dly_shift_3_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_3_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.dly_shift_3_DSTATE)), sizeof(int) * 138);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_4_DSTATE = {187};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.dly_shift_4_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_4_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.dly_shift_4_DSTATE)), sizeof(int) * 187);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_5_DSTATE = {199};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.dly_shift_5_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_dly_shift_5_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.dly_shift_5_DSTATE)), sizeof(int) * 199);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_g;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_g", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_g, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_g)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_a;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_a", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_a, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_a)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_n;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_n", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_n, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_n)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_a;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_a", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_a, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_a)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_i;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_i", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_i, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_i)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_f;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_f", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_f, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_f)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_e;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_e", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_e, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_e)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_c;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_c", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_c, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_c)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_c;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_c", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_c, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_c)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_e5;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_e5", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_e5, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_e5)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter1_states = {576};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter1_states", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter1_states, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter1_states)), sizeof(int) * 576);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter3_states = {352};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter3_states", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter3_states, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter3_states)), sizeof(int) * 352);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter4_states = {254};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter4_states", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter4_states, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter4_states)), sizeof(int) * 254);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter5_states = {230};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.DiscreteFIRFilter5_states", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_DiscreteFIRFilter5_states, (char*)(&(DynamicCompressionModel_DW_instance.DiscreteFIRFilter5_states)), sizeof(int) * 230);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_j;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_j", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay1_DSTATE_j, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay1_DSTATE_j)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_l;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_l", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_l, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_l)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_o;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ram_data_DSTATE_o", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ram_data_DSTATE_o, (char*)(&(DynamicCompressionModel_DW_instance.ram_data_DSTATE_o)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_h;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_h", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_h, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_h)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE = {3};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.Delay_DSTATE)), sizeof(int) * 3);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_n;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_n", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_n, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_n)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_g;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_g", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_g, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_g)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_e = {3};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay_DSTATE_e", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_e, (char*)(&(DynamicCompressionModel_DW_instance.Delay_DSTATE_e)), sizeof(int) * 3);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_d;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_d", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_d, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_d)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_gj;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_gj", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_gj, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_gj)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_n = {3};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay_DSTATE_n", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_n, (char*)(&(DynamicCompressionModel_DW_instance.Delay_DSTATE_n)), sizeof(int) * 3);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_a;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_a", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_a, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_a)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_m;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_m", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_m, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_m)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_d = {3};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay_DSTATE_d", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_d, (char*)(&(DynamicCompressionModel_DW_instance.Delay_DSTATE_d)), sizeof(int) * 3);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_gu;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_gu", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_gu, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_gu)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_m2;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_m2", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay_DSTATE_m2, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay_DSTATE_m2)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_p = {3};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay_DSTATE_p", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay_DSTATE_p, (char*)(&(DynamicCompressionModel_DW_instance.Delay_DSTATE_p)), sizeof(int) * 3);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_ig65fir_states = {288};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.ig65fir_states", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_ig65fir_states, (char*)(&(DynamicCompressionModel_DW_instance.ig65fir_states)), sizeof(int) * 288);
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_h;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_h", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_h, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_h)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_hj;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_hj", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_hj, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_hj)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_m;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_m", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_m, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_m)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_e;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_e", "i32", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay2_DSTATE_e, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay2_DSTATE_e)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay2_DSTATE", "u32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.Delay2_DSTATE)), sizeof(unsigned int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_g;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay2_DSTATE_g", "u32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_g, (char*)(&(DynamicCompressionModel_DW_instance.Delay2_DSTATE_g)), sizeof(unsigned int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_a;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay2_DSTATE_a", "u32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_a, (char*)(&(DynamicCompressionModel_DW_instance.Delay2_DSTATE_a)), sizeof(unsigned int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_n;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay2_DSTATE_n", "u32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_n, (char*)(&(DynamicCompressionModel_DW_instance.Delay2_DSTATE_n)), sizeof(unsigned int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_nl;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Delay2_DSTATE_nl", "u32", arraySizeOf_DynamicCompressionModel_DW_instance_Delay2_DSTATE_nl, (char*)(&(DynamicCompressionModel_DW_instance.Delay2_DSTATE_nl)), sizeof(unsigned int));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_Count_reg_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.Count_reg_DSTATE", "u16", arraySizeOf_DynamicCompressionModel_DW_instance_Count_reg_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.Count_reg_DSTATE)), sizeof(unsigned short));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE", "u16", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE)), sizeof(unsigned short));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_d;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_d", "u16", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_d, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_d)), sizeof(unsigned short));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_i;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_i", "u16", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_i, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_i)), sizeof(unsigned short));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_c;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_c", "u16", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_c, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_c)), sizeof(unsigned short));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_o;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_o", "u16", arraySizeOf_DynamicCompressionModel_DW_instance_UnitDelay3_DSTATE_o, (char*)(&(DynamicCompressionModel_DW_instance.UnitDelay3_DSTATE_o)), sizeof(unsigned short));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_pp_Delay_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.fxpt_lzc_W32_pp.Delay_DSTATE", "u8", arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_pp_Delay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.fxpt_lzc_W32_pp.Delay_DSTATE)), sizeof(unsigned char));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_p_Delay_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.fxpt_lzc_W32_p.Delay_DSTATE", "u8", arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_p_Delay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.fxpt_lzc_W32_p.Delay_DSTATE)), sizeof(unsigned char));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_l_Delay_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.fxpt_lzc_W32_l.Delay_DSTATE", "u8", arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_l_Delay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.fxpt_lzc_W32_l.Delay_DSTATE)), sizeof(unsigned char));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_c_Delay_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.fxpt_lzc_W32_c.Delay_DSTATE", "u8", arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_c_Delay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.fxpt_lzc_W32_c.Delay_DSTATE)), sizeof(unsigned char));
    vector<int> arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_Delay_DSTATE;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_DW_instance.fxpt_lzc_W32.Delay_DSTATE", "u8", arraySizeOf_DynamicCompressionModel_DW_instance_fxpt_lzc_W32_Delay_DSTATE, (char*)(&(DynamicCompressionModel_DW_instance.fxpt_lzc_W32.Delay_DSTATE)), sizeof(unsigned char));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1, (char*)(&(DynamicCompressionModel_B_instance.Subtract1)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_n;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_n", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_n, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_n)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_i;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_i", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_i, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_i)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_k;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_k", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_k, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_k)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_a;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_a", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_a, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_a)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_d;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_d", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_d, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_d)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_b;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_b", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_b, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_b)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_nh;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_nh", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_nh, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_nh)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_ax;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_ax", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_ax, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_ax)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_ku;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_B_instance.Subtract1_ku", "i32", arraySizeOf_DynamicCompressionModel_B_instance_Subtract1_ku, (char*)(&(DynamicCompressionModel_B_instance.Subtract1_ku)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_PrevZCX_instance;
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_PrevZCX_instance", "i32", arraySizeOf_DynamicCompressionModel_PrevZCX_instance, (char*)(&(DynamicCompressionModel_PrevZCX_instance)), sizeof(int));
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_ig65fir_Coefficients = {289};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.ig65fir_Coefficients", "i32", arraySizeOf_DynamicCompressionModel_ConstP_ig65fir_Coefficients, (char*)(&(DynamicCompressionModel_ConstP.ig65fir_Coefficients)), sizeof(int) * 289);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_pooled19 = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.pooled19", "i32", arraySizeOf_DynamicCompressionModel_ConstP_pooled19, (char*)(&(DynamicCompressionModel_ConstP.pooled19)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_pooled20 = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.pooled20", "i32", arraySizeOf_DynamicCompressionModel_ConstP_pooled20, (char*)(&(DynamicCompressionModel_ConstP.pooled20)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_pooled21 = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.pooled21", "i32", arraySizeOf_DynamicCompressionModel_ConstP_pooled21, (char*)(&(DynamicCompressionModel_ConstP.pooled21)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_pooled22 = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.pooled22", "i32", arraySizeOf_DynamicCompressionModel_ConstP_pooled22, (char*)(&(DynamicCompressionModel_ConstP.pooled22)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_pooled23 = {512};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.pooled23", "i32", arraySizeOf_DynamicCompressionModel_ConstP_pooled23, (char*)(&(DynamicCompressionModel_ConstP.pooled23)), sizeof(int) * 512);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter2_Coefficients = {629};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.DiscreteFIRFilter2_Coefficients", "i32", arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter2_Coefficients, (char*)(&(DynamicCompressionModel_ConstP.DiscreteFIRFilter2_Coefficients)), sizeof(int) * 629);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter1_Coefficients = {577};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.DiscreteFIRFilter1_Coefficients", "i32", arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter1_Coefficients, (char*)(&(DynamicCompressionModel_ConstP.DiscreteFIRFilter1_Coefficients)), sizeof(int) * 577);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter3_Coefficients = {353};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.DiscreteFIRFilter3_Coefficients", "i32", arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter3_Coefficients, (char*)(&(DynamicCompressionModel_ConstP.DiscreteFIRFilter3_Coefficients)), sizeof(int) * 353);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter4_Coefficients = {255};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.DiscreteFIRFilter4_Coefficients", "i32", arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter4_Coefficients, (char*)(&(DynamicCompressionModel_ConstP.DiscreteFIRFilter4_Coefficients)), sizeof(int) * 255);
    vector<int> arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter5_Coefficients = {231};
    TCGHybrid::registGlobalVariables("DynamicCompressionModel_ConstP.DiscreteFIRFilter5_Coefficients", "i32", arraySizeOf_DynamicCompressionModel_ConstP_DiscreteFIRFilter5_Coefficients, (char*)(&(DynamicCompressionModel_ConstP.DiscreteFIRFilter5_Coefficients)), sizeof(int) * 231);
}
